jobs:
  checks-website:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - continue-on-error: true
      name: Test Build
      run: 'yarn install --frozen-lockfile

        npm run build

        '
      working-directory: ./website
  deploy-website:
    if: github.repository == 'apache/submarine' && github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - continue-on-error: true
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      name: Add key to allow access to repository
      run: 'mkdir -p ~/.ssh

        ssh-keyscan github.com >> ~/.ssh/known_hosts

        echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa

        chmod 600 ~/.ssh/id_rsa

        '
    - continue-on-error: true
      env:
        DEPLOYMENT_BRANCH: asf-site
        GIT_USER: pingsutw
        USE_SSH: true
      name: Deploy Submarine website
      run: 'git config --global user.email "pingsutw@apache.org"

        git config --global user.name "pingsutw"

        yarn install --frozen-lockfile

        yarn deploy

        '
      working-directory: ./website
name: Deploy Submarine documentation
on:
  repository_dispatch:
    types: trigger-ga___deploy_website.yml
