jobs:
  deploy-builtin-images:
    env:
      SUBMARINE_VERSION: 0.9.0-SNAPSHOT
    if: github.repository == 'apache/submarine'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: apache/submarine
    - continue-on-error: true
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      name: Build submarine jupyter
      run: ./dev-support/docker-images/jupyter/build.sh
    - continue-on-error: true
      name: Push submarine-jupyter docker image
      run: 'docker push apache/submarine:jupyter-notebook-$SUBMARINE_VERSION

        docker rmi apache/submarine:jupyter-notebook-$SUBMARINE_VERSION

        '
    - continue-on-error: true
      name: Build submarine jupyter gpu
      run: ./dev-support/docker-images/jupyter-gpu/build.sh
    - continue-on-error: true
      name: Push submarine-jupyter-gpu docker image
      run: 'docker push apache/submarine:jupyter-notebook-gpu-$SUBMARINE_VERSION

        docker rmi apache/submarine:jupyter-notebook-gpu-$SUBMARINE_VERSION

        '
    - continue-on-error: true
      name: Build submarine mlflow
      run: ./dev-support/docker-images/mlflow/build.sh
    - continue-on-error: true
      name: Push submarine-mlflow docker image
      run: 'docker push apache/submarine:mlflow-$SUBMARINE_VERSION

        docker rmi apache/submarine:mlflow-$SUBMARINE_VERSION

        '
    - continue-on-error: true
      name: Build submarine quickstart
      run: ./dev-support/examples/quickstart/build.sh
    - continue-on-error: true
      name: Push submarine quickstart docker image
      run: 'docker push apache/submarine:quickstart-$SUBMARINE_VERSION

        docker rmi apache/submarine:quickstart-$SUBMARINE_VERSION

        '
    timeout-minutes: 240
  deploy-cloud-native-and-cicd:
    env:
      SUBMARINE_VERSION: 0.9.0-SNAPSHOT
    if: github.repository == 'apache/submarine'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: apache/submarine
    - continue-on-error: true
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      name: Build submarine operator
      run: ./dev-support/docker-images/operator-v3/build.sh
    - continue-on-error: true
      name: Push submarine-operator docker image
      run: 'docker push apache/submarine:operator-$SUBMARINE_VERSION

        docker rmi apache/submarine:operator-$SUBMARINE_VERSION

        '
    - continue-on-error: true
      name: Build submarine cicd
      run: ./dev-support/cicd/build.sh
    - continue-on-error: true
      name: Push submarine-cicd docker image
      run: 'docker push apache/submarine:cicd-$SUBMARINE_VERSION

        docker rmi apache/submarine:cicd-$SUBMARINE_VERSION

        '
    timeout-minutes: 240
  deploy-server:
    env:
      SUBMARINE_VERSION: 0.9.0-SNAPSHOT
    if: github.repository == 'apache/submarine'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: apache/submarine
    - continue-on-error: true
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - continue-on-error: true
      name: Set up Maven 3.6.3
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.6.3
    - continue-on-error: true
      name: Check version
      run: 'mvn --version

        java -version

        '
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -DskipTests
    - continue-on-error: true
      name: Build submarine server
      run: ./dev-support/docker-images/submarine/build.sh
    - continue-on-error: true
      name: Push submarine-server docker image
      run: 'docker push apache/submarine:server-$SUBMARINE_VERSION

        docker rmi apache/submarine:server-$SUBMARINE_VERSION

        '
    - continue-on-error: true
      name: Build submarine agent
      run: ./dev-support/docker-images/agent/build.sh
    - continue-on-error: true
      name: Push submarine-agent docker image
      run: 'docker push apache/submarine:agent-$SUBMARINE_VERSION

        docker rmi apache/submarine:agent-$SUBMARINE_VERSION

        '
    - continue-on-error: true
      name: Build submarine database
      run: ./dev-support/docker-images/database/build.sh
    - continue-on-error: true
      name: Push submarine-database docker image
      run: 'docker push apache/submarine:database-$SUBMARINE_VERSION

        docker rmi apache/submarine:database-$SUBMARINE_VERSION

        '
    timeout-minutes: 240
name: Deploy submarine docker images
on:
  repository_dispatch:
    types: trigger-ga___deploy_docker_images.yml
