jobs:
  jupyter-images:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Build submarine jupyter
      run: ./dev-support/docker-images/jupyter/build.sh
    - continue-on-error: true
      name: Build submarine jupyter gpu
      run: ./dev-support/docker-images/jupyter-gpu/build.sh
    timeout-minutes: 240
name: Building jupyter images
on:
  repository_dispatch:
    types: trigger-ga___jupyter_images.yml
